CREATE DATABASE IF NOT EXISTS FEC;
 USE FEC;
 DROP TABLE IF EXISTS individual_contributions_v2;
 CREATE TABLE individual_contributions_v2(
 CMTE_ID VARCHAR(9) COMMENT 'Filer Identification Number',
 AMNDT_IND VARCHAR(1) COMMENT 'Amendment Indicator',
 RPT_TP VARCHAR(3) COMMENT 'Report Type',
 TRANSACTION_PGI VARCHAR(5) COMMENT 'Primary-General Indicator',
 IMAGE_NUM VARCHAR(11) COMMENT 'Microfilm Location (YYOORRRFFFF)',
 TRANSACTION_TP VARCHAR(3) COMMENT 'Transaction Type',
 ENTITY_TP VARCHAR(3) COMMENT 'Entity Type',
 NAME VARCHAR(200) COMMENT 'Contributor/Lender/Transfer Name',
 CITY VARCHAR(30) COMMENT 'City/Town',
 STATE VARCHAR(2) COMMENT 'State',
 ZIP_CODE VARCHAR(9) COMMENT 'Zip Code',
 EMPLOYER VARCHAR(38) COMMENT 'Employer',
 OCCUPATION VARCHAR(38) COMMENT 'Occupation',
 TRANSACTION_DT VARCHAR(10) COMMENT 'Transaction Date(MMDDYYYY)',
 TRANSACTION_AMT FLOAT(14,2) COMMENT 'Transaction Amount',
 OTHER_ID VARCHAR(9) COMMENT 'Other Identification Number',
 TRAN_ID VARCHAR(32) COMMENT 'Transaction ID',
 FILE_NUM VARCHAR(22) COMMENT 'File Number / Report ID',
 MEMO_CD VARCHAR(1) COMMENT 'Memo Code',
 MEMO_TEXT VARCHAR(100) COMMENT 'Memo Text',
 SUB_ID VARCHAR(19) COMMENT 'FEC Record Number',
 
 KEY TRAN_INDEX (TRAN_ID,CMTE_ID)
 );

